name: Enforce main branch source rules

on:
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Ensure PR comes from dev
        run: |
          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "Only dev branch can be merged into main"
            exit 1
          fi